spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/QXBlog?useSSL=true&characterEncoding=utf-8
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
  #    show-sql: true

  thymeleaf:
    mode: HTML

  profiles:
    active: dev
